# Generated by Django 4.0.1 on 2022-01-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expectations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managingexpectation',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
