version: "3"

services:
  db:
    image: 'postgres:latest'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=managing_expectation_user
      - POSTGRES_PASSWORD=managing123
      - POSTGRES_DB=managing_expectation_db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
    links:
      - db:db