# Base image
FROM node:16-alpine as base

# Set working directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install --production

# Copy app files
COPY . .

# Expose the port on which the app will be running
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
