# Generated by Django 4.1.1 on 2022-10-01 17:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("duration", models.TimeField()),
                ("description", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "calories_burnt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        default="Deleted User",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="athlete_exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_exercises",
                        to="equipments.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
