# Generated by Django 4.1.1 on 2022-10-02 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0002_alter_equipment_created_at"),
        ("exercises", "0003_alter_exercise_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="equipment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="equipment_exercises",
                to="equipments.equipment",
            ),
            preserve_default=False,
        ),
    ]
