# Generated by Django 4.1.1 on 2022-10-02 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exercises", "0004_alter_exercise_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="athlete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="athlete_exercises",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
