version: '3'

services:
    web:
        build: 
            dockerfile: docker/Dockerfile
            context: .
        env_file: 
            - .env
        container_name: gym-service-backend
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        volumes:
            - .:/app
    
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - PGDATA=/var/lib/postgresql/data
        ports:
            - "5433:5432"
        volumes:
            - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: